### PR TITLE
Downgrade *mongoose* due to production connection failure

### PR DESCRIPTION
**Pull request by Martii**
* Hopefully this fixes this... not present in dev environment

``` sh-session
connection error: { [MongoError: no valid seed servers in list] name: 'MongoError', message: 'no valid seed servers in list' }
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at MongoStore.addListener (events.js:179:15)
    at MongoStore.once (events.js:204:8)
    at MongoStore.getCollection (/home/oujs/OpenUserJS.org/node_modules/connect-mongo/lib/connect-mongo.js:219:16)
    at MongoStore.get (/home/oujs/OpenUserJS.org/node_modules/connect-mongo/lib/connect-mongo.js:285:10)
    at session (/home/oujs/OpenUserJS.org/node_modules/express-session/index.js:404:11)
    at Layer.handle [as handle_request] (/home/oujs/OpenUserJS.org/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/oujs/OpenUserJS.org/node_modules/express/lib/router/index.js:312:13)
    at /home/oujs/OpenUserJS.org/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/oujs/OpenUserJS.org/node_modules/express/lib/router/index.js:330:12)
    at next (/home/oujs/OpenUserJS.org/node_modules/express/lib/router/index.js:271:10)
    at initialize (/home/oujs/OpenUserJS.org/node_modules/passport/lib/middleware/initialize.js:62:5)
    at Layer.handle [as handle_request] (/home/oujs/OpenUserJS.org/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/oujs/OpenUserJS.org/node_modules/express/lib/router/index.js:312:13)
    at /home/oujs/OpenUserJS.org/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/oujs/OpenUserJS.org/node_modules/express/lib/router/index.js:330:12)
    at next (/home/oujs/OpenUserJS.org/node_modules/express/lib/router/index.js:271:10)
```

### CODE REVIEW

**Comment by Martii** [comment]
@sizzlemctwizzle 
Please investigate this.

**Comment by Martii** [comment]
@sizzlemctwizzle 
Please be advised that this may hose production from running due to a different failure of *bson* not being found... finally got it running after several retries with current dev GH HEAD

**Comment by sizzlemctwizzle** [comment]
Those error messages are from connect-mongo, not mongoose. I did upgrade the database to MongoDB v3.0.5

**Comment by Martii** [comment]
> I did upgrade the database to MongoDB v3.0.5

Does this mean this shouldn't happen again on this specific versioning? We were down for about 25 minutes and I got several *bson* errors.

**Comment by Martii** [comment]
What's even more unusual is that I didn't do *connect-mongo* as a dep migration. :\

**Comment by sizzlemctwizzle** [comment]
connect-mongo shares the connection established by mongoose.

**Pull request merged**
