### PR TITLE
Some doc fixes

### PR DESCRIPTION
**Pull request by Martii**
* Typo, image reference updates, etc.

NOTES:
* Some pages don't exist yet
* Donating the text version of my Compatibility Matrix to OUJS

### CODE REVIEW

**Comment by Martii** [comment]
Both TM and VM for Android don't appear to work but do install... will probably remove these from the TOC.

**Comment by Martii** [comment]
And confirmed the iOS has **zero** browsers that support Userscripts. That's too bad.

**Comment by derjanb** [comment]
> TM and VM for Android don't appear to work but do install

@Martii Not sure if this is what you've tested, but [Tampermonkey Firefox](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) at [Firefox Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en) is supported by me and working fine here.

**Comment by Martii** [comment]
@derjanb 

> is supported by me and working fine here.

Forgot to add the Fx label to that comment... oujs - Meta View on Android 8.0.0 *(Samsung Galaxy S8)* with Fx latest didn't show me the Meta e.g. Script injection appeared to not work. Until I set my dev station up for remote debugging to my device and see what's going on I won't be able to create an issue for you. Have to check my source first but since it works on several other platforms I highly doubt it's my Userscript. Works in GM too in the same browser.

**Comment by Martii** [comment]
Did find https://adguard.com/en/adguard-ios/overview.html for iOS however it looks like it's pay ... unfortunately my friends iPhone isn't available at the moment to check.

**Comment by Martii** [comment]
Hmmm Win10 just said Edge is available for iOS... more for the todo list.

**Comment by Martii** [comment]
@derjanb 
So the exact issue is that it just shows script source and doesn't give me the installation prompt *(no viable hook for it is my guess)*. 

This weekend I'll set up remote debugging and see if there are any console messages and come bug you if needed.

**Pull request merged**
