### PR TITLE
Release the hounds

### PR DESCRIPTION
**Pull request by Martii**
* Adapt for cacheable .user.js engines vs non
* Few implementation bug fixes... e.g. it's **even stricter** when a .user.js engine doesn't allow caching
* Still using ES6 `let` in this section of code

NOTES:
* This is really going to point out the bug in upstream GM
* Almost back to original logic of `sendScript`

Applies to #944

### CODE REVIEW

**Comment by Martii** [comment]
Some stats for this PR tested on production:

* Greasemonkey Port 3.10.0.1rc*3*pre-sm.xpi ... **okay**
* greasemonkey-3.12.1beta4-pm_forkBranch_experimental.xpi ... **will show** 429's until PM 27.3.0 ... **but managed**. Cc: @janekptacijarabaci
* TM *Beta* v4.3.5430 ... **okay** Cc: @derjanb
* Violent Monkey ... for Presto with VM v1.7.3.1 and newer WebKit Opera of VM v2.5.7 ... **okay**... never had an issue presumably from violentmonkey/violentmonkey-oex#40 and violentmonkey/violentmonkey-oex#40 *(perhaps another)*. Cc: @gera2ld Nice work and major Kudos!! :)
* Greasemonkey 3.10.0 release... **is booged** and will send extra request after 429 Re: greasemonkey/greasemonkey#2390 and #989 Cc: @arantius
* QupZilla latest ... **okay** when viewing script source and then closing window and redoing it again. Cc: @nowrep Nice work and major Kudos too!! :)

If testing during the *express-brute* period in multiple, different, browsers may get a 429 since a different browser already retrieved it... this part untested at the moment but if a 429 shows up then it's expected.

**Comment by arantius** [comment]
Again, GM 3.x is not going to change.  GM 4.x if it exists might take this into account.

Perhaps the best solution would be putting yourself behind CloudFlare and letting them absorb the load?

**Comment by Martii** [comment]
## Test URL
https://githubs.com/anonim1133/wykop-userjs/blob/a86014414395f71e2b9f930cf8ec876374808c24/wykop-zawijas.user.js

## Test UserAgent
`Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 SeaMonkey/2.46`

### GM Port 3.10.0...RC1 *(near parlallel of GM)*

#### Error Console

```
Timestamp: 04/12/2017 03:24:34 PM
Error: NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIChannel.contentType]
Source File: chrome://greasemonkey-modules/content/remoteScript.js
Line: 170
```

#### Console

``` sh-session
$ ./seamonkey
aRequest is neither http nor file channel: [xpconnect wrapped (nsISupports, nsIChannel, nsIRequest, nsIHttpChannel)]
it is a: nsIStreamListener
it is a: nsIHttpChannel
it is a: nsISupportsWeakReference
it is a: nsITraceableChannel
it is a: nsIProtocolProxyCallback
it is a: nsIChannel
it is a: nsIWritablePropertyBag2
it is a: nsIPrivateBrowsingChannel
it is a: nsIUploadChannel
it is a: nsIDNSListener
it is a: nsIRequest
it is a: nsITransportEventSink
it is a: nsIClassOfService
it is a: nsIEncodedChannel
it is a: nsIProxiedChannel
it is a: nsICacheInfoChannel
it is a: nsIPropertyBag2
it is a: nsIApplicationCacheContainer
it is a: nsICacheEntryOpenCallback
it is a: nsIHttpChannelInternal
it is a: nsIHttpAuthenticableChannel
it is a: nsIRequestObserver
it is a: nsIFormPOSTActionChannel
it is a: nsISupports
it is a: nsICachingChannel
it is a: nsIAsyncVerifyRedirectCallback
it is a: nsIWritablePropertyBag
it is a: nsIApplicationCacheChannel
it is a: nsIUploadChannel2
it is a: nsISupportsPriority
it is a: nsIResumableChannel
it is a: nsIPropertyBag
it is a: nsITimedChannel
```

... code point of [greasemonkey/greasemonkey/blob/`696848a`/modules/remoteScript.js#L197](https://github.com/greasemonkey/greasemonkey/blob/696848acc40c6395904a53acdc15a653d5be502c/modules/remoteScript.js#L197)

#### Screenshot

SM with GM Port RC1

### GM Port 3.10.0...RC2/RC3 *(slight veer from GM)*


#### Error Console
No error in Error Console 

#### Console

``` sh-session
$ ./seamonkey
aRequest is neither http nor file channel: [xpconnect wrapped (nsISupports, nsIChannel, nsIRequest, nsIHttpChannel)]
it is a: nsIStreamListener
it is a: nsIHttpChannel
it is a: nsISupportsWeakReference
it is a: nsITraceableChannel
it is a: nsIProtocolProxyCallback
it is a: nsIChannel
it is a: nsIWritablePropertyBag2
it is a: nsIPrivateBrowsingChannel
it is a: nsIUploadChannel
it is a: nsIDNSListener
it is a: nsIRequest
it is a: nsITransportEventSink
it is a: nsIClassOfService
it is a: nsIEncodedChannel
it is a: nsIProxiedChannel
it is a: nsICacheInfoChannel
it is a: nsIPropertyBag2
it is a: nsIApplicationCacheContainer
it is a: nsICacheEntryOpenCallback
it is a: nsIHttpChannelInternal
it is a: nsIHttpAuthenticableChannel
it is a: nsIRequestObserver
it is a: nsIFormPOSTActionChannel
it is a: nsISupports
it is a: nsICachingChannel
it is a: nsIAsyncVerifyRedirectCallback
it is a: nsIWritablePropertyBag
it is a: nsIApplicationCacheChannel
it is a: nsIUploadChannel2
it is a: nsISupportsPriority
it is a: nsIResumableChannel
it is a: nsIPropertyBag
it is a: nsITimedChannel
```

... code point of [greasemonkey/greasemonkey/blob/`696848a`/modules/remoteScript.js#L197](https://github.com/greasemonkey/greasemonkey/blob/696848acc40c6395904a53acdc15a653d5be502c/modules/remoteScript.js#L197)

#### Screenshot

SM with GM Port RC3

Too bad it looks like GM 3.x is going to be left booged like this without greasemonkey/greasemonkey#2415 and it's successive patches... which fixes a portion of the outdated cache disabling issue too.

Misc quote for the day: 

> Don't let it end this way.

<cite>Chancellor Gorkon</cite>

**Comment by janekptacijarabaci** [comment]
Ad "Unable to connect":
https://github.com/greasemonkey/greasemonkey/pull/2494

**Comment by Martii** [comment]
For those interested... PM 27.3.0 is out and works like a charm... one bugged .user.js engine to go. :)

**Pull request merged**
