### PR TITLE
Change to *colors* dep

### PR DESCRIPTION
**Pull request by Martii**
* Really could have used a little better initial explanation for chalk/chalk#110

Not to mention the lack of nicety I just got with the lock... we don't want bad support maintainers for sure.

*colors* is longer lived anyhow.

### CODE REVIEW

**Comment by Martii** [comment]
@Qix-

Thanks for the explaination... wish your other maintainer would have been a little more agreeable.

**Comment by tunnckoCore** [comment]
Better consider using https://github.com/doowb/ansi-colors. `colors` is too bad.

**Comment by Martii** [comment]
I'll look into that for sure... thanks for the tip... we don't use the console coloring much other than a few messages so it's not super critical at this time. :)

**Comment by Qix-** [comment]
What is the specific problem you're facing with chalk? O.o As we mentioned in the other thread, the version number mismatch shouldn't be a huge problem.

---

And to defend Sindre, we faced a lot of traffic with the release problems that stressed both of us out. The emergency mentioned wasn't either of our fault and I know I was up for 12 hours straight watching the issue tracker trying to find anyone having problems to help fix them (we get several million downloads a month - chalk *can't* go wrong).

He also has hundreds of other modules he has to deal with on a daily basis, so he's pretty spread thin :) I can gladly help you with any Chalk problems you're having, though.

**Comment by tunnckoCore** [comment]
So if that's the case absolutely better would be to use not ansi-colors, but what `ansi-*` you need. If you plan to use more and more colors `ansi-colors` is good pretendent.

**Comment by Martii** [comment]
@Qix-

> What is the specific problem you're facing with chalk?

Validation of sources is one of my responsibilities... just was asking why it was out of sync... and I got a rude, although concise initially point to a commit, response from a maintainer and then the lock while I was asking a question... I thought I was being respectful and didn't get that in return.

You can defend him all you want but the damage is done. Still is a cool project we just need a little more agreeableness. I wanted to approach your repo ~3 weeks ago but not everyone is receptive to issues... we avoid those when possible. [Here's an example of good responses](https://github.com/github/octicons/issues/45).

**Comment by Martii** [comment]
> The emergency mentioned wasn't either of our fault and I know I was up for 12 hours

I can relate to our 2 week ordeal with TamperMonkey... but please don't take it out on us. I didn't take it out on that maintainer... everyone makes mistakes is one of my mottos.

**Comment by Qix-** [comment]
@Martii To be fair, locking of issues is quite common on Github simply due to volume. It wasn't a rude thing by any means, even if it seemed like it. It also prevents grave digging in the future and forces people to open new issues, simply because the use cases might have changed between versions and thus someone commenting on a 6 month old issue (thread) may have similar symptoms but a completely different cause, and grave digging an old issue either clutters up the tracker or causes their comments to go unnoticed completely.

---

We're aware of it being out of sync :+1: It's not ideal but it is what it is. Our next release will most likely be a major release anyway since we're hoping to land 256/16 million color support soon-ish (in fact, that functionality has been implemented in `ansi-styles` and is what was released there that caused the problems in the first place).

**Comment by Martii** [comment]
@Qix- 
Well it sounds like you've had your share of bad responses but in all reality I was just asking some questions. If that's *chalk*s policy then I am relatively sure the whole team here won't be receptive to opening different issues within seconds and I have no desire to contribute there anymore... we have our own work-flow to maintain... other projects don't have this issue that your team does e.g. they listen first... wait a little while instead of acting irrationally.... then close when the fluff of dust settles.

That's great that you'll be in master sync repo at some point. Good luck to you guys.

**Comment by Qix-** [comment]
@Martii I'm not sure what else you want me to do, here. I've been all but helpful and inquisitive about the nature of your _specific_ problem. I am not Sindre, so being upset with me isn't going to get either of us anywhere 👯 

As I mentioned before, and as I have since confirmed directly with Sindre, we locked it to prevent unrelated spam in the issue itself. It was nothing against you, personally.

I don't believe I'm acting irrationally to any of this but if I am please let me know :+1: Chalk's policy is to be chalk. We're not a company or a business, nor are we backed by one. We're two developers that have never met in real life - not unlike most of the development world. Communication is key and we do whatever we can to maximize the signal to noise ratio.

I hope that makes sense.

**Comment by Martii** [comment]
> I am not Sindre, so being upset with me isn't going to get either of us anywhere

Who said I was upset with you specifically?... I've actually thanked you and wished you guys good luck.

> we locked it to prevent unrelated spam in the issue itself. It was nothing against you, personally.

In the middle of a resolution that's not a wise choice to make... plus I'm not spam. :)

> I don't believe I'm acting irrationally to any of this

You aren't... that is directed to the locker of the issue. You've been agreeable here although a few insinuations but I can live with those... just wish you could have stepped in before your other maintainer did... our mutual loss here.

**Comment by Qix-** [comment]
Heh, no problem. :+1: I tried.

**Comment by Martii** [comment]
LOL... now that you've gone back and reedited the posts to change the meaning of things... I can see why you've had so many issues. I was tracking your changes btw... this will merit a lock of this one... I've also restored some of your comments to their original nature.

**Pull request merged**
