### PR TITLE
Some dep updates

### PR DESCRIPTION
**Pull request by Martii**
* Delete op retested
* CSS min retested

### CODE REVIEW

**Comment by Martii** [comment]
Source absent on install button... thought this was just a dev issue but appears to be one of the deps. Reverted to original clone for diagnosis on current HEAD.

**Comment by Martii** [comment]
Seems like it's an *aws-sdk* dep failure ... only present on full reinstall of all deps... confirming with secondary testing...

**Comment by Martii** [comment]
Secondary testing results in *express-minify* appearing to be the culprit... reverting until further investigation.

**Comment by Martii** [comment]
Source install button present on dev... pushing to pro shortly...

**Comment by Martii** [comment]
Confirmed... current HEAD okay minus *express-minify* update on pro. Will investigate in a bit.

**Comment by kincaider** [comment]
840d1b6

**Pull request merged**
