### PR TITLE
A dep downgrade

### PR DESCRIPTION
**Pull request by Martii**
* *express-minify* may have broken a few things... reverting

Post #1158 fix

### CODE REVIEW

**Comment by kincaider** [comment]
a523b06

**Comment by Martii** [comment]
@kincaider
The commit hash is already in this PR. Look right below the CODE and migration labels. 

Please do not rereference it again. 
Thanks.

**Comment by kincaider** [comment]
a523b06

**Comment by Martii** [comment]
@kincaider 
You've been banned from dev.

**Pull request merged**
