### PR TITLE
Silently migrate from OpenID to OAuth2 authentication for Google.

### LINKED ISSUE #484: Google OpenID Deprecation
More info:
* https://support.google.com/accounts/answer/6135882
* https://developers.google.com/accounts/docs/OpenID#shutdown-timetable
* https://www.npmjs.org/package/passport-google
* https://github.com/jaredhanson/passport-google/issues/25

Solutions:
* https://github.com/jaredhanson/passport-google-oauth
* https://www.npmjs.org/package/passport-google-oauth-2
* https://www.npmjs.org/package/passport-google-auth
* https://www.npmjs.org/package/passport-google-oauth2
* http://iao.fi/myposts/passport_google_openid_migration

### PR DESCRIPTION
**Pull request by sizzlemctwizzle**
Closes #484.

### CODE REVIEW

**Comment by Martii** [comment]
Test driving shortly. I assume that pro is offline until this is deployed so give me a few moments to check out the PR and see if it's all peachy with another account. I separated my pro account to only be GH so I should be able to see migration as well as new account creation.

**Comment by sizzlemctwizzle** [comment]
Whoops I spaced on new account creation. Give me some time to make sure that code won't explode.

**Comment by Martii** [comment]
k... appears that the stored `auths` item is the same value on dev for my google account... didn't expect that but it did reprompt me to access my profile instead of the usual deprecation warning I was getting and jerone used to create the issue.

**Comment by sizzlemctwizzle** [comment]
Okay, I've tested signing up under the new OAuth code and changing your default to the Google strategy. I already migrated my OpenID accounts on development, so I can't retest my migration.

**Comment by Martii** [comment]
> changing your default to the Google strategy

Marti is my GH account on dev and Martii is my google account on dev... so hopefully we don't have a conflict now with that. I didn't write down my GH auth value on dev. :\

**Comment by Martii** [comment]
Hmmm... running a local pro on the latest HEAD of this PR here and `Google` doesn't appear in the drop down. If this goes to nodejitsu pro it may also not show up for new account creation.

**Comment by sizzlemctwizzle** [comment]
I just put the api creds in and now it appears on production locally.

**Comment by Martii** [comment]
Hmmm just got a 404 on account creation on local pro.

**Comment by sizzlemctwizzle** [comment]
Because I set the callback up for production.

**Comment by Martii** [comment]
durr it's late... hehe... forgot to change that to localhost

**Comment by Martii** [comment]
New account creation corroborated. See pro `@Martii` ... let's give this a shot on nodejitsu pro.... merging. I can roll back the snapshot back tomorrow if it fails at any point and you are unavailable.

**Comment by Martii** [comment]
Before deploy we might want to bump the project [version](https://github.com/OpenUserJs/OpenUserJS.org/blob/master/package.json#L4) number too to `0.1.7+0000000` so we know that a rollback could have consequences with this strategy after merged/deployed/live

**Pull request merged**
