### PR TITLE
Some dep updates

### PR DESCRIPTION
**Pull request by Martii**
* bug fixes, etc... please read their CHANGELOGs
* Fix README.md linkage

**NOTES**
* Waiting on *jquery* ... usually major releases are a bit too buggy.

### CODE REVIEW

**Comment by Martii** [comment]
Hmmm...

``` bash
$ npm --depth 0 outdated
Package                       Current            Wanted      Latest  Location
...
mongodb                        2.1.21            2.1.21      2.1.18  mongodb
...
```

**Comment by Martii** [comment]
jQuery 3.0.0 definitely isn't working with *express* modals in a retest.

**Comment by christkv** [comment]
There are some issues related to 2.1.19-21 that makes it not ideal for upgrade. Instead of pulling them I set 2.1.18 as latest to avoid people pulling them less they explicitly want to. I'm working on a 2.2.0 driver that contains refactorings to address the core issues.

**Comment by Martii** [comment]
Okee dokee... thanks... so far in the last 10 days it's been status quo with the dep that needs this with .21 but haven't dug real deep into it.

**Comment by Martii** [comment]
*jquery* and *bootstrap* modal incompatibility fixed in dev *bootstrap* with [twbs/bootstrap#20338](https://github.com/twbs/bootstrap/pull/20338). Hopefully the next v3.x release of *bootstrap* will be soon as it is stalling normative migration. Since jQuery is a known dependent and confirmed as being:

DaSchTour [wrote](https://github.com/twbs/bootstrap/issues/19809#issuecomment-215019414):
> It's an error in package.json

... an error as "missing" in  doing an issue reference to #904

Also from the last time modals were touched the modal demo at http://getbootstrap.com/javascript/#static-example has changed a bit.

Adding mitigation watchpoint.

**Pull request merged**
